spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mohirdev_employe
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 4040

security:
  jwt:
    secret-key: verysecret
    expiration-time: 3600000